### ISSUE TITLE
paginate posts

### ISSUE THREAD

**Issue by hussamEL-Hwary** [hussamEL-Hwary/blog#2]
Instead of getting the latest added posts,  I will get posts in parts.
[https://docs.djangoproject.com/en/2.2/topics/pagination/](check this)

**Comment by erdepe-dad** [comment]
i already create pull request for this issue @hussamEL-Hwary please review. Thank you

**Comment by hussamEL-Hwary** [comment]
Thanks @ahmadsyafrudin
